### ISSUE TITLE
Which version of Node.js has been certified(will be used) for this project? 

### ISSUE THREAD

**Issue by Kish-Jadhav** [OSLC/oslc-server#4]
Hi,

Which version of node.js should be used for this project? Are we certifying any version? where can i find this document?

**Comment by jamsden** [comment]
I used the available version at the time. I’d suggest exploring the key dependencies to determine what version to update to, including all the dependencies in the package.json files. Probably the key dependency will be rdflib.js.

**Comment by Kish-Jadhav** [comment]
When I have checked the package.js from ldp-service, the node "engines" shows the node version "node": "~5.1.0".
I believe this is the version that we can consider and this package.js will be upgraded as an when these modules will be verified/used with latest node versions.

FYI. Could you please label these type of questions with label "question", it would be helpful for end user to identify the open issues and questions.

**Comment by jamsden** [comment]
Currently using 10.6.0. These need to be updated in all the OSLC4 modules.
